"""Pure domain logic for PL-2000 cadastral area calculations."""

from .calculation import (
    M0,
    Q1,
    Q2,
    Q3,
    Q4,
    SIGMA0_CM_PER_KM,
    calculate_area,
    calculate_area_from_pgk,
    calculate_pgk,
    epsg_for_zone,
    pl2000_point_from_qgis_coordinates,
    round_area_ha,
    unique_boundary_points,
    validate_easting_zone,
    zone_for_epsg,
    zone_prefix_from_easting,
)
from .errors import (
    AreaCalculationError,
    EmptyBoundaryPointsError,
    InvalidAreaError,
    InvalidZoneError,
    NonFiniteValueError,
    UnsupportedPl2000CrsError,
    ZoneMismatchError,
)
from .models import AreaCalculationResult, Pl2000BoundaryPoint

__all__ = [
    "M0",
    "Q1",
    "Q2",
    "Q3",
    "Q4",
    "SIGMA0_CM_PER_KM",
    "AreaCalculationError",
    "AreaCalculationResult",
    "EmptyBoundaryPointsError",
    "InvalidAreaError",
    "InvalidZoneError",
    "NonFiniteValueError",
    "Pl2000BoundaryPoint",
    "UnsupportedPl2000CrsError",
    "ZoneMismatchError",
    "calculate_area",
    "calculate_area_from_pgk",
    "calculate_pgk",
    "epsg_for_zone",
    "pl2000_point_from_qgis_coordinates",
    "round_area_ha",
    "unique_boundary_points",
    "validate_easting_zone",
    "zone_for_epsg",
    "zone_prefix_from_easting",
]
